name: Bug Report
description: Report an issue or bug impacting your workflow.
title: "[BUG]: Brief Title"
labels: ["bug", "triage"]
assignees: []  
body:
  - type: input
    id: customer_name
    attributes:
      label: Customer Name
      description: "Name of the customer experiencing the issue."
      placeholder: "Example: ABC Corp."
    validations:
      required: true
  
  - type: textarea
    id: contacts
    attributes:
      label: Contacts
      description: "List any persons to notify about this feedback. (Github username or email.)"
      placeholder: "Joey Brown - joeybrown@mondoo.com github:joeB"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Description of the Issue
      description: "Describe what happened, including the impacted features or providers."
      placeholder: "Provide a detailed description of the bug."
    validations:
      required: true

  - type: dropdown
    id: business_impact
    attributes:
      label: Business Impact
      description: "Rate the impact of this issue on your business. See [Prioritization](tab=readme-ov-file#prioritization) for further details."
      multiple: false
      options:
        - P1 - Blocker (critical impact)
        - P2 - Major (significant impact)
        - P3 - Minor (low impact)
        - P4 - Cosmetic (very low)
    validations:
      required: true

  - type: textarea
    id: troubleshooting_steps
    attributes:
      label: Troubleshooting Steps & Workarounds
      description: "Describe any troubleshooting steps and/or workarounds you’ve taken so far.  Please add any relevant screenshots, logs, links, etc.\n\nFor scans, please run in debug mode using `DEBUG=1 cnspec scan <target asset>` and attach all `mondoo-debug` files."
    validations:
      required: true
      
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide detailed steps we can take to reproduce the issue."
      placeholder: "Example: 1. Go to '...'; 2. Click on '...'; 3. Observe the error."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versions
      description: "Output of `cnquery version` & `cnspec version`."
      placeholder: "cnquery: 1.0.0, cnspec 2.2.2"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Any additional context or information that may help resolve the issue."
      
  - type: markdown
    attributes:
      value: "### Thank you for your submission!"
