---
  name: Feature Request
  description: New Features or Improvement to the product.
  title: "[FEATURE] Brief Title"
  labels: ["enhancement", "triage"]
  assignees: []  
  body:
    - type: input
      id: customer_name
      attributes:
        label: Customer Name
        description: "Name of the customer requesting the feature."
        placeholder: "Example: Mondoo"
      validations:
        required: true

    - type: textarea
      id: contacts
      attributes:
        label: Contacts
        description: "List any persons to notify about this feedback. (Github username or email.)"
        placeholder: "Joey Brown - joeybrown@mondoo.com github:joeB"
      validations:
        required: true

    - type: dropdown
      id: permission_to_contact
      attributes:
        label: Permission to Contact
        description: "Can the Product or Engineering Team reach out to you for further clarification?"
        multiple: false
        options:
          - "Yes"
          - "No"
      validations:
        required: true
  
    - type: textarea
      id: feature_description
      attributes:
        label: Feature Description
        description: "Describe the requested feature in detail, including the intended outcome and specific functionality."
      validations:
        required: true
  
    - type: dropdown
      id: business_importance
      attributes:
        label: Business Importance
        description: "Rate the importance of this feature for your business needs."
        multiple: false
        options:
          - Blocker (critical need)
          - High (important for business initiatives)
          - Medium (enhancement request)
          - Low (nice to have)
      validations:
        required: true

    - type: dropdown
      id: impact
      attributes:
        label: Impact
        description: "Is the absence of this feature blocking your work?"
        multiple: false
        options:
          - YES, BLOCKER 🚫
          - NO, BUT IMPROVES EFFICIENCY ⬆️
          - NO, GENERAL ENHANCEMENT 🌸
      validations:
        required: true
  
    - type: textarea
      id: workarounds
      attributes:
        label: Workarounds
        description: "Describe any workarounds you're currently using or have tried.\n Please attach any relevant artifacts such as screenshots, links, code, etc."
  
    - type: textarea
      id: additional_context
      attributes:
        label: Additional Context
        description: "Any additional context or information that may help in implementing this feature."

    - type: markdown
      attributes:
        value: "### Thank you for your submission!"
